import type { AppState } from '../types'

export const VISUAL_NOW = '2026-09-19T20:00:00.000Z'
export const VISUAL_DAY = '2026-09-19'
export const VISUAL_USER_ID = 'visual-ada'

export const VISUAL_USER = {
  sub: VISUAL_USER_ID,
  email: 'ada@poiem.test',
  name: 'Ada Chen',
  provider: 'email' as const,
}

/** Fixed account used by visual captures: three meals and one weigh-in. */
export function visualSeedState(): AppState {
  return {
    onboarded: true,
    profile: {
      name: 'Ada Chen',
      gender: 'female',
      birthday: '1998-03-12',
      heightCm: 168,
      weightKg: 62,
      activityLevel: 'moderate',
      goal: 'maintain',
      weeklyChangeKg: 0.5,
      customCalories: 2000,
      customProtein: 110,
      customCarbs: 220,
      customFat: 65,
      soundEnabled: false,
      hapticsEnabled: false,
      mascotMuted: false,
      mascotReducedMotion: true,
      mascotRoasts: false,
      trackingPaused: false,
      loggingCommitment: 'light',
    },
    foodEntries: [
      {
        id: 'seed-oats',
        name: 'Overnight oats',
        calories: 320,
        protein: 12,
        carbs: 52,
        fat: 8,
        timestamp: '2026-09-19T08:15:00.000Z',
        localDate: VISUAL_DAY,
        source: 'manual',
        mealType: 'breakfast',
        emoji: '🥣',
      },
      {
        id: 'seed-bowl',
        name: 'Chicken rice bowl',
        calories: 540,
        protein: 38,
        carbs: 48,
        fat: 16,
        timestamp: '2026-09-19T12:40:00.000Z',
        localDate: VISUAL_DAY,
        source: 'manual',
        mealType: 'lunch',
        emoji: '🍗',
      },
      {
        id: 'seed-soup',
        name: 'Tomato soup',
        calories: 280,
        protein: 8,
        carbs: 32,
        fat: 10,
        timestamp: '2026-09-19T18:20:00.000Z',
        localDate: VISUAL_DAY,
        source: 'manual',
        mealType: 'dinner',
        emoji: '🍲',
      },
    ],
    weightEntries: [
      { id: 'seed-weight', date: '2026-09-19T07:00:00.000Z', weightKg: 62 },
    ],
    exerciseEntries: [],
    favoriteMeals: [
      {
        id: 'seed-saved-oats',
        name: 'Overnight oats',
        calories: 320,
        protein: 12,
        carbs: 52,
        fat: 8,
        mealType: 'breakfast',
        emoji: '🥣',
      },
    ],
    chatMessages: [],
    aiSettings: {
      accessMode: 'managed',
      provider: 'openrouter',
      apiKey: '',
      model: 'google/gemini-2.5-flash',
      mascotEnabled: true,
      mascotPersonality: 'warm',
    },
    gamification: {
      xp: 40,
      level: 1,
      streakFreezes: 1,
      freezeUsedDates: [],
      freezeEarnedMonth: '2026-09',
      pauseStartedDate: null,
      pauseProtectedDates: [],
      xpEvents: [
        { id: 'seed-xp-1', key: 'first-meal-2026-09-19', xp: 10, label: 'First meal', timestamp: '2026-09-19T08:15:00.000Z' },
        { id: 'seed-xp-2', key: 'meal-seed-oats', xp: 10, label: 'Logged a meal', timestamp: '2026-09-19T08:15:00.000Z' },
        { id: 'seed-xp-3', key: 'meal-seed-bowl', xp: 10, label: 'Logged a meal', timestamp: '2026-09-19T12:40:00.000Z' },
        { id: 'seed-xp-4', key: 'meal-seed-soup', xp: 10, label: 'Logged a meal', timestamp: '2026-09-19T18:20:00.000Z' },
      ],
      awardedKeys: [
        'first-meal-2026-09-19',
        'meal-seed-oats',
        'meal-seed-bowl',
        'meal-seed-soup',
        'three-meals-2026-09-19',
      ],
      pendingLevelUp: null,
      seenBadgeIds: [],
      gems: 0,
      gemEvents: [],
      waterByDate: { [VISUAL_DAY]: 3 },
      notesByDate: {},
      ownedCosmeticIds: ['blossom'],
      equippedCosmeticId: null,
      outfit: { head: 'blossom' },
      repairsUsedMonth: '',
      mascotActivity: 'calm',
      brokenOn: null,
      brokenFrom: 0,
      startedAt: '2026-09-01T12:00:00.000',
    },
  }
}
