import { expect, test } from '@playwright/test'
import { settlePageLayout, signUpAndOnboard } from './helpers'

for (const width of [320, 390, 768, 1280]) {
  test(`You page stays useful and expressive at ${width}px`, async ({ page }, testInfo) => {
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    await page.route('**/api/**', route => route.abort('blockedbyclient'))
    await page.setViewportSize({ width, height: 900 })
    await page.emulateMedia({ reducedMotion: 'reduce' })
    await signUpAndOnboard(page)
    await page.goto('/settings')
    await expect(page.getByRole('heading', { name: 'You', exact: true })).toBeVisible()
    for (const colorScheme of ['light', 'dark'] as const) {
      await page.emulateMedia({ colorScheme })
      await page.reload()
      await expect(page.locator('html')).toHaveAttribute('data-theme', colorScheme)
      await expect(page.getByRole('link', { name: 'Momo' })).toBeVisible()
      await page.getByRole('link', { name: 'Momo' }).click()
      await expect(page.getByRole('heading', { name: 'Your kitchen companion' })).toBeVisible()
      await page.getByRole('switch', { name: 'Mute Momo' }).setChecked(colorScheme === 'light')
      await page.getByRole('switch', { name: 'Reduce Momo motion' }).setChecked(colorScheme === 'light')
      await page.getByRole('button', { name: 'Save settings' }).click()
      await expect(page.getByRole('status').filter({ hasText: 'Settings saved' })).toBeVisible()
      await settlePageLayout(page)
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
      await page.screenshot({ path: testInfo.outputPath(`you-${colorScheme}.png`), fullPage: true, animations: 'disabled' })
    }
    expect(errors).toEqual([])
  })
}

test('settings search supports keyboard jumps, recovery and unsaved preferences', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.route('**/api/**', route => route.abort('blockedbyclient'))
  await signUpAndOnboard(page)
  await page.goto('/settings')
  const finder = page.getByRole('search', { name: 'Find settings' })
  const search = finder.getByRole('searchbox', { name: 'Find a setting' })
  await search.fill('dark mode')
  await search.press('Tab')
  await expect(finder.getByRole('button', { name: 'Clear settings search' })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(finder.getByRole('link', { name: /Appearance/ })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.locator('#you-appearance')).toBeFocused()
  await expect(search).toHaveValue('')

  await search.fill('momo')
  await finder.getByRole('link', { name: /Momo/ }).click()
  await expect(page.locator('#you-momo')).toBeFocused()
  await page.getByRole('switch', { name: 'Mute Momo' }).setChecked(true)
  await search.fill('password')
  await finder.getByRole('link', { name: /Account/ }).click()
  await expect(page.locator('#you-account')).toBeFocused()
  await expect(page.getByRole('status').filter({ hasText: 'Unsaved changes' })).toBeVisible()
  await page.getByRole('link', { name: 'Momo', exact: true }).first().click()
  await expect(page.getByRole('switch', { name: 'Mute Momo' })).toBeChecked()

  await search.fill('xyz-no-match')
  await expect(finder.getByRole('status')).toContainText('No match yet')
  await expect(finder.getByRole('link')).toHaveCount(0)
  await finder.getByRole('button', { name: 'Clear settings search' }).click()
  await expect(search).toBeFocused()
  await expect(search).toHaveValue('')
  await search.fill('reset')
  await search.press('Escape')
  await expect(search).toHaveValue('')
  await expect(finder.getByRole('link')).toHaveCount(0)
  await search.fill('AI key')
  await expect(finder.getByRole('link', { name: /AI setup/ })).toBeVisible()
})
