import { expect, test } from '@playwright/test'
import { birthdayYearsAgo, clearAppStorage, completeOnboarding, openYouDestination, signInWithEmail, signUp, signUpAndOnboard } from './helpers'

test('deliberate sign-out clears return navigation while preserving the account journal', async ({ page }) => {
  const credentials = await signUpAndOnboard(page)
  await page.goto('/settings?panel=account')
  await expect(page.getByRole('button', { name: 'Sign out', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await expect(page).toHaveURL('/login')
  expect(await page.evaluate(() => sessionStorage.getItem('poiem-session-return-v1'))).toBeNull()
  await signInWithEmail(page, credentials.email, credentials.password)
  await expect(page).toHaveURL('/')
  await expect(page.locator('.k-meal-row').filter({ hasText: 'Onboarding yogurt bowl' })).toBeVisible()
})

test('an explicit setup handoff keeps guest choices when creating an unconfigured account', async ({ page }) => {
  await clearAppStorage(page)
  await page.goto('/onboarding')
  await page.getByRole('button', { name: 'Get started', exact: true }).click()
  await page.getByLabel('Date of birth').fill(birthdayYearsAgo(25))
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Your body', exact: true })).toBeVisible()
  await page.getByLabel('Height (cm)', { exact: true }).fill('182')
  await page.getByRole('link', { name: 'Already a member? Sign in', exact: true }).click()
  await expect(page).toHaveURL('/login?setup=1')
  await signUp(page)
  await expect(page.getByRole('heading', { name: 'Your body', exact: true })).toBeVisible()
  await expect(page.getByLabel('Height (cm)', { exact: true })).toHaveValue('182')
  const copies = await page.evaluate(() => Object.keys(localStorage).filter(key => key.startsWith('fud-onboarding-draft-')))
  expect(copies).toHaveLength(2)
})

test('an existing completed account wins over a guest setup handoff', async ({ page }) => {
  await clearAppStorage(page)
  const credentials = await signUp(page, { name: 'Existing journal' })
  await completeOnboarding(page)
  await page.getByLabel('Main').getByRole('link', { name: 'You', exact: true }).click()
  await openYouDestination(page, 'Account')
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await page.goto('/onboarding')
  await page.getByRole('button', { name: 'Get started', exact: true }).click()
  await page.getByLabel('Date of birth').fill(birthdayYearsAgo(25))
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await page.getByLabel('Height (cm)', { exact: true }).fill('182')
  await page.getByRole('link', { name: 'Already a member? Sign in', exact: true }).click()
  await signInWithEmail(page, credentials.email, credentials.password)
  await expect(page).toHaveURL('/')
  await expect(page.locator('.k-meal-row').filter({ hasText: 'Onboarding yogurt bowl' })).toBeVisible()
  await page.goto('/settings?panel=profile')
  await expect(page.getByRole('spinbutton', { name: 'Height', exact: true })).toHaveValue('175')
})
