import { expect, test, type Page } from '@playwright/test'
import { nav, openYouDestination, signUpAndOnboard } from './helpers'

async function appliedSettings(page: Page) {
  return page.evaluate(async () => {
    const user = JSON.parse(localStorage.getItem('fud-ai-auth-session') ?? 'null') as { sub: string } | null
    if (!user) throw new Error('Expected signed-in account')
    const moduleUrl = '/src/lib/durableState.ts'
    const { loadDurableState } = await import(moduleUrl)
    const saved = await loadDurableState(user.sub)
    if (!saved) throw new Error('Expected device snapshot')
    return saved.state
  })
}

async function draftConnection(page: Page, auth: 'none' | 'api-key' = 'none') {
  await openYouDestination(page, 'AI setup')
  await page.getByRole('switch', { name: 'Use my own API', exact: true }).check()
  await page.getByLabel('API endpoint', { exact: true }).fill('https://custom-ai.example/v1/chat/completions')
  await page.getByLabel('Model', { exact: true }).fill('test-vision')
  await page.locator('.you-api-auth > summary').click()
  await page.getByRole('combobox', { name: 'Authentication method', exact: true }).selectOption(auth)
  await page.locator('.you-api-auth > summary').click()
}

const departure = (page: Page) => page.getByRole('dialog', { name: 'Keep your Settings changes?', exact: true })

test.beforeEach(async ({ page }) => {
  await page.route('**/api/**', route => route.abort('blockedbyclient'))
  await page.route('https://custom-ai.example/**', route => route.abort('blockedbyclient'))
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await signUpAndOnboard(page)
  await page.goto('/settings?panel=profile')
})

test('Stay, Escape and backdrop keep both drafts while panel and search navigation remain free', async ({ page }) => {
  await page.getByRole('textbox', { name: 'Name', exact: true }).fill('Draft name')
  await draftConnection(page)
  await openYouDestination(page, 'Preferences')
  await page.getByRole('switch', { name: 'Sound', exact: true }).uncheck()
  await nav(page).getByRole('link', { name: 'Insights' }).click()
  await expect(departure(page).getByRole('button', { name: 'Stay', exact: true })).toBeFocused()
  await expect(departure(page)).toContainText('Unsaved profile and AI changes')
  await page.keyboard.press('Escape')
  await expect(departure(page)).toBeHidden()
  await nav(page).getByRole('link', { name: 'Insights' }).click()
  await page.locator('.k-sheet-backdrop').click({ position: { x: 5, y: 5 } })
  await expect(departure(page)).toBeHidden()
  await page.getByRole('searchbox', { name: 'Find a setting' }).fill('name')
  await page.getByRole('search', { name: 'Find settings' }).getByRole('link', { name: /^Name/ }).click()
  await expect(page.getByRole('textbox', { name: 'Name', exact: true })).toHaveValue('Draft name')
  await openYouDestination(page, 'AI setup')
  await expect(page.getByLabel('Model', { exact: true })).toHaveValue('test-vision')
  await expect.poll(async () => (await appliedSettings(page)).profile.soundEnabled).toBe(false)
  expect((await appliedSettings(page)).aiSettings.accessMode).toBe('managed')
})

test('Discard leaves with the current applied values and keeps immediate preferences', async ({ page }) => {
  const before = await appliedSettings(page)
  await page.getByRole('spinbutton', { name: 'Height', exact: true }).fill('182')
  await draftConnection(page)
  await openYouDestination(page, 'Preferences')
  await page.getByRole('switch', { name: 'Haptics', exact: true }).uncheck()
  await nav(page).getByRole('link', { name: 'Insights' }).click()
  await departure(page).getByRole('button', { name: 'Discard and leave', exact: true }).click()
  await expect(page).toHaveURL(/\/progress$/)
  await nav(page).getByRole('link', { name: 'You', exact: true }).click()
  await openYouDestination(page, 'Profile & goals')
  await expect(page.getByRole('spinbutton', { name: 'Height', exact: true })).toHaveValue(String(before.profile.heightCm))
  await expect(page.getByRole('button', { name: 'Save settings', exact: true })).toHaveCount(0)
  await expect.poll(async () => (await appliedSettings(page)).profile.hapticsEnabled).toBe(false)
  expect((await appliedSettings(page)).aiSettings.accessMode).toBe('managed')
})

test('Save applies both drafts and resumes the Log sheet with its original background state', async ({ page }) => {
  await page.getByRole('spinbutton', { name: 'Height', exact: true }).fill('181')
  await draftConnection(page)
  await page.getByTestId('fab').click()
  await expect(departure(page)).toBeVisible()
  await departure(page).getByRole('button', { name: 'Save and leave', exact: true }).click()
  await expect(page).toHaveURL(/\/log$/)
  await expect(page.getByRole('dialog', { name: 'Log a meal', exact: true })).toBeVisible()
  await expect(page.locator('.k-you')).toBeVisible()
  await expect.poll(async () => (await appliedSettings(page)).profile.heightCm).toBe(181)
  await expect.poll(async () => (await appliedSettings(page)).aiSettings.accessMode).toBe('byok')
  await page.keyboard.press('Escape')
  await expect(page).toHaveURL(/\/settings\?panel=ai$/)
  await expect(page.getByRole('button', { name: 'Save settings', exact: true })).toHaveCount(0)
})

test('invalid profile from another panel focuses Height and applies neither draft', async ({ page }) => {
  const before = await appliedSettings(page)
  await page.getByRole('spinbutton', { name: 'Height', exact: true }).fill('0')
  await draftConnection(page)
  await nav(page).getByRole('link', { name: 'Insights' }).click()
  await departure(page).getByRole('button', { name: 'Save and leave', exact: true }).click()
  await expect(page).toHaveURL(/\/settings\?panel=profile$/)
  await expect(page.getByRole('spinbutton', { name: 'Height', exact: true })).toBeFocused()
  await expect(page.getByRole('spinbutton', { name: 'Height', exact: true })).toHaveValue('0')
  expect((await appliedSettings(page)).profile.heightCm).toBe(before.profile.heightCm)
  expect((await appliedSettings(page)).aiSettings.accessMode).toBe('managed')
  await openYouDestination(page, 'AI setup')
  await expect(page.getByLabel('Model', { exact: true })).toHaveValue('test-vision')
})

test('invalid AI opens the auth disclosure, focuses its field and preserves a valid profile draft', async ({ page }) => {
  const before = await appliedSettings(page)
  await page.getByRole('spinbutton', { name: 'Height', exact: true }).fill('181')
  await draftConnection(page, 'api-key')
  await page.locator('.you-api-auth > summary').click()
  await page.getByLabel('Key header name', { exact: true }).fill('content-type')
  await page.locator('.you-api-auth > summary').click()
  await openYouDestination(page, 'Momo')
  await nav(page).getByRole('link', { name: 'Insights' }).click()
  await departure(page).getByRole('button', { name: 'Save and leave', exact: true }).click()
  await expect(page).toHaveURL(/\/settings\?panel=ai$/)
  await expect(page.locator('.you-api-auth')).toHaveAttribute('open', '')
  await expect(page.getByLabel('Key header name', { exact: true })).toBeFocused()
  await expect(page.getByRole('alert')).toContainText('Use the header your provider expects')
  expect((await appliedSettings(page)).profile.heightCm).toBe(before.profile.heightCm)
  expect((await appliedSettings(page)).aiSettings.accessMode).toBe('managed')
  await openYouDestination(page, 'Profile & goals')
  await expect(page.getByRole('spinbutton', { name: 'Height', exact: true })).toHaveValue('181')
})

test('Forward can Stay and resumes the pending in-app history destination', async ({ page }) => {
  await nav(page).getByRole('link', { name: 'Insights' }).click()
  await page.goBack()
  await expect(page).toHaveURL(/\/settings\?panel=profile$/)
  await page.getByRole('spinbutton', { name: 'Height', exact: true }).fill('181')
  await page.evaluate(() => history.forward())
  await expect(departure(page)).toBeVisible()
  await departure(page).getByRole('button', { name: 'Stay', exact: true }).click()
  await expect(page).toHaveURL(/\/settings\?panel=profile$/)
  await page.evaluate(() => history.forward())
  await expect(departure(page)).toBeVisible()
  await departure(page).getByRole('button', { name: 'Discard and leave', exact: true }).click()
  await expect(page).toHaveURL(/\/progress$/)
  await page.goBack()
  await expect(page).toHaveURL(/\/settings\?panel=profile$/)
  await expect(page.getByRole('spinbutton', { name: 'Height', exact: true })).toHaveValue('175')
})

test('Back keeps drafts through panel history and protects the previous app route', async ({ page }) => {
  await page.goto('/')
  await nav(page).getByRole('link', { name: 'You', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'You', exact: true })).toBeVisible()
  await openYouDestination(page, 'Profile & goals')
  await page.getByRole('spinbutton', { name: 'Height', exact: true }).fill('181')
  await page.evaluate(() => history.back())
  await expect(page).toHaveURL(/\/settings$/)
  await expect(page.getByRole('button', { name: 'Save settings', exact: true })).toBeVisible()
  await page.evaluate(() => history.back())
  await expect(departure(page)).toBeVisible()
  await departure(page).getByRole('button', { name: 'Stay', exact: true }).click()
  await expect(page).toHaveURL(/\/settings$/)
  await page.evaluate(() => history.back())
  await expect(departure(page)).toBeVisible()
  await departure(page).getByRole('button', { name: 'Discard and leave', exact: true }).click()
  await expect(page).toHaveURL(/localhost:5194\/$/)
  await page.goForward()
  await expect(page).toHaveURL(/\/settings$/)
  await expect(page.getByRole('button', { name: 'Save settings', exact: true })).toHaveCount(0)
})

test('only dirty drafts register browser departure protection; immediate preferences stay freely navigable', async ({ page }) => {
  const preventsUnload = () => page.evaluate(() => {
    const event = new Event('beforeunload', { cancelable: true })
    window.dispatchEvent(event)
    return event.defaultPrevented
  })
  expect(await preventsUnload()).toBe(false)
  await openYouDestination(page, 'Preferences')
  await page.getByRole('switch', { name: 'Sound', exact: true }).uncheck()
  expect(await preventsUnload()).toBe(false)
  await openYouDestination(page, 'Profile & goals')
  await page.getByRole('spinbutton', { name: 'Height', exact: true }).fill('181')
  expect(await preventsUnload()).toBe(true)
  await page.getByRole('button', { name: 'Save settings', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save settings', exact: true })).toHaveCount(0)
  expect(await preventsUnload()).toBe(false)
  await nav(page).getByRole('link', { name: 'Insights' }).click()
  await expect(page).toHaveURL(/\/progress$/)
  await expect(departure(page)).toHaveCount(0)
})

test('intentional sign-out offers Stay or Discard and never promises Save during sign-out', async ({ page }) => {
  await page.getByRole('textbox', { name: 'Name', exact: true }).fill('Pending signout name')
  await draftConnection(page, 'api-key')
  await page.getByRole('textbox', { name: 'API key', exact: true }).fill('pending-dummy-secret')
  await openYouDestination(page, 'Account')
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Sign out with unsaved changes?', exact: true })
  await expect(dialog.getByRole('button', { name: 'Stay', exact: true })).toBeFocused()
  await expect(dialog).toContainText('Stay and Save settings before signing out')
  await expect(dialog.getByRole('button', { name: /Save and/ })).toHaveCount(0)
  await dialog.getByRole('button', { name: 'Stay', exact: true }).click()
  await openYouDestination(page, 'AI setup')
  await expect(page.getByRole('textbox', { name: 'API key', exact: true })).toHaveValue('pending-dummy-secret')
  await openYouDestination(page, 'Account')
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await dialog.getByRole('button', { name: 'Discard and sign out', exact: true }).click()
  await expect(page).toHaveURL(/\/login$/)
  await expect(page.getByRole('textbox', { name: 'API key', exact: true })).toHaveCount(0)
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('forced account expiry bypasses a pending prompt and removes secret drafts', async ({ page }) => {
  await draftConnection(page, 'api-key')
  await page.getByRole('textbox', { name: 'API key', exact: true }).fill('pending-expiry-secret')
  await nav(page).getByRole('link', { name: 'Insights' }).click()
  await expect(departure(page)).toBeVisible()
  await page.evaluate(() => {
    localStorage.removeItem('fud-ai-auth-session')
    window.dispatchEvent(new StorageEvent('storage', { key: 'fud-ai-auth-session', newValue: null }))
  })
  await expect(page).toHaveURL(/\/login$/)
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('textbox', { name: 'API key', exact: true })).toHaveCount(0)
  expect(await page.evaluate(() => Object.values(sessionStorage).some(value => value.includes('pending-expiry-secret')))).toBe(false)
})

for (const width of [320, 390, 1440]) for (const colorScheme of ['light', 'dark'] as const) {
  test(`departure choices fit ${width}px ${colorScheme} at short keyboard height`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height: width === 1440 ? 900 : 400 })
    await page.emulateMedia({ colorScheme })
    await page.getByRole('spinbutton', { name: 'Height', exact: true }).fill('181')
    await nav(page).getByRole('link', { name: 'Insights' }).click()
    const dialog = departure(page)
    await expect(dialog).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    for (const label of ['Stay', 'Save and leave', 'Discard and leave']) {
      const control = dialog.getByRole('button', { name: label, exact: true })
      await control.scrollIntoViewIfNeeded()
      const box = await control.boundingBox()
      expect(box?.height).toBeGreaterThanOrEqual(44)
      expect(box?.x).toBeGreaterThanOrEqual(0)
      expect((box?.x ?? width) + (box?.width ?? 0)).toBeLessThanOrEqual(width)
    }
    await page.screenshot({ path: testInfo.outputPath(`settings-departure-${width}-${colorScheme}.png`), animations: 'disabled' })
    await page.keyboard.press('Escape')
    await expect(dialog).toBeHidden()
  })
}
